1. Load Clinical Excel

In [2]:
import pandas as pd
import numpy as np

# Load file
clinical_path = "../01_Data_Raw/Tabular_Dataset/TOMPEI-CMMD_clinical_data_v01_20250121.xlsx"
df = pd.read_excel(clinical_path, sheet_name="Imaging Diagnosis Details Sheet")

print(df.columns)
df.head()

Index(['ID', 'LeftRight', 'Age', 'classification', 'Unnamed: 4',
       'Breast density', 'Mass', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Calcification', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Other findings',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'BI-RADS\nCategory',
       'Notes', 'Mass - Additional Lesion', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28',
       'Calcification - Additional Lesion', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32'],
      dtype='object')

,ID,LeftRight,Age,classification,Unnamed: 4,Breast density,Mass,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Mass - Additional Lesion,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Calcification - Additional Lesion,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,NaN,NaN,NaN,NaN,Exclusion reasons,NaN,Location,Shape,Margin,Density,...,Location,Shape,Margin,Density,Associated calcification,Other Associated Findings,Location,Morphology,Distribution,Clearly Benign Calcifications
1,D1-0001,R,44.0,Benign,NaN,heterogeneous dense,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,D1-0002,L,40.0,Benign,NaN,heterogeneous dense,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,D1-0003,L,39.0,Benign,NaN,scattered,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,D1-0004,L,41.0,Benign,NaN,heterogeneous dense,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

2. Edit Rows & Columns Manually

In [3]:
# Removing Row 0 because it contains sub-headers for merged columns
df = df.drop(index=0).reset_index(drop=True)
# Renaming Columns Properly
df = df.rename(columns={
    "Unnamed: 4": "Exclusion reasons",
    "Mass": "Mass_Location",
    "Unnamed: 7": "Mass_Shape",
    "Unnamed: 8": "Mass_Margin",
    "Unnamed: 9": "Mass_Density",
    "Unnamed: 10": "Mass_Associated_calcification",
    "Unnamed: 11": "Mass_Other_Associated_Findings",
    "Calcification": "Calc_Location",
    "Unnamed: 13": "Calc_Morphology",
    "Unnamed: 14": "Calc_Distribution",
    "Unnamed: 15": "Calc_Clearly_Benign",
    "BI-RADS\nCategory": "BI_RADS"
})

print(df.columns)
df.head()

Index(['ID', 'LeftRight', 'Age', 'classification', 'Exclusion reasons',
       'Breast density', 'Mass_Location', 'Mass_Shape', 'Mass_Margin',
       'Mass_Density', 'Mass_Associated_calcification',
       'Mass_Other_Associated_Findings', 'Calc_Location', 'Calc_Morphology',
       'Calc_Distribution', 'Calc_Clearly_Benign', 'Unnamed: 16',
       'Other findings', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'BI_RADS', 'Notes', 'Mass - Additional Lesion', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28',
       'Calcification - Additional Lesion', 'Unnamed: 30', 'Unnamed: 31',
       'Unnamed: 32'],
      dtype='object')

,ID,LeftRight,Age,classification,Exclusion reasons,Breast density,Mass_Location,Mass_Shape,Mass_Margin,Mass_Density,...,Mass - Additional Lesion,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Calcification - Additional Lesion,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,D1-0001,R,44.0,Benign,NaN,heterogeneous dense,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,D1-0002,L,40.0,Benign,NaN,heterogeneous dense,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,D1-0003,L,39.0,Benign,NaN,scattered,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,D1-0004,L,41.0,Benign,NaN,heterogeneous dense,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,D1-0005,R,42.0,Benign,NaN,extremely dense,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

3. Remove Unnecessary Columns

In [4]:
columns_to_keep = [
    "ID",
    "LeftRight",
    "Age",
    "classification",
    "Exclusion reasons",
    "Breast density",
    "BI_RADS",
    "Mass_Location",
    "Mass_Shape",
    "Mass_Margin",
    "Mass_Density",
    "Mass_Associated_calcification",
    "Mass_Other_Associated_Findings",
    "Calc_Location",
    "Calc_Morphology",
    "Calc_Distribution",
    "Calc_Clearly_Benign"
]

df = df[columns_to_keep].copy()

print(df.columns)
df.head()

Index(['ID', 'LeftRight', 'Age', 'classification', 'Exclusion reasons',
       'Breast density', 'BI_RADS', 'Mass_Location', 'Mass_Shape',
       'Mass_Margin', 'Mass_Density', 'Mass_Associated_calcification',
       'Mass_Other_Associated_Findings', 'Calc_Location', 'Calc_Morphology',
       'Calc_Distribution', 'Calc_Clearly_Benign'],
      dtype='object')

,ID,LeftRight,Age,classification,Exclusion reasons,Breast density,BI_RADS,Mass_Location,Mass_Shape,Mass_Margin,Mass_Density,Mass_Associated_calcification,Mass_Other_Associated_Findings,Calc_Location,Calc_Morphology,Calc_Distribution,Calc_Clearly_Benign
0,D1-0001,R,44.0,Benign,NaN,heterogeneous dense,2.0,NaN,NaN,NaN,NaN,NaN,NaN,M,Small Round Calcification,regional,NaN
1,D1-0002,L,40.0,Benign,NaN,heterogeneous dense,2.0,NaN,NaN,NaN,NaN,NaN,NaN,U-M,Small Round Calcification,regional,NaN
2,D1-0003,L,39.0,Benign,NaN,scattered,3.0,NaN,NaN,NaN,NaN,NaN,NaN,M,Amorphous and indistinct calcification,grouped,NaN
3,D1-0004,L,41.0,Benign,NaN,heterogeneous dense,2.0,NaN,NaN,NaN,NaN,NaN,NaN,M,Small Round Calcification,regional,NaN
4,D1-0005,R,42.0,Benign,NaN,extremely dense,2.0,NaN,NaN,NaN,NaN,NaN,NaN,L,Small Round Calcification,regional,NaN

4. Remove Exclusions